### ISSUE TITLE
Out of date Satis

### ISSUE THREAD

**Issue by Jamesking56** [ochorocho/gitlab-pages-satis#1]
This docker image produces a Satis repository which is outdated (`1.0.0-dev`).

Can this and the fork it uses of `satis-gitlab` be updated to the latest version?

**Comment by ochorocho** [comment]
Hey, thanks. I hope to get the time to update this by tomorrow.

**Comment by Jamesking56** [comment]
Thanks mate :+1:

**Comment by ochorocho** [comment]
Seems like this is only a template issue:
https://github.com/composer/satis/blob/f66ff72ce4e788e95827404888fd53b3c9d29f82/src/Satis.php#L19

With the next release satis version it should show the right version in the template

**Comment by Jamesking56** [comment]
Oh I see so it is using the latest version, excellent

**Comment by ochorocho** [comment]
I updated all packages related to gitlab-pages-satis and the docker container.
See https://hub.docker.com/r/ochorocho/gitlab-pages-satis/

**Comment by Jamesking56** [comment]
Thanks, will close for now unless the version number doesn't change when Satis updates
